SheridanLibrary/Controllers/CartController.cs
using SheridanLibrary.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SheridanLibrary.Controllers
{
   
    public class CartController : Controller
    {
        private const string BOOK_SESSION = "BookCart";
        private Library _library;

        public CartController()
        {
            _library = new Library();
        }
        public BookCart _bookCart
        {
            get
            {
                BookCart cart = Session[BOOK_SESSION] as BookCart;
                if(cart == null)
                {
                    cart = new BookCart();
                    Session[BOOK_SESSION] = cart;
                }
                return cart;
            }
        }

        
        // GET: Cart
        public ActionResult Index(string ReturnUrl)
        {
            ViewBag.ReturnUrl = ReturnUrl;
            return View(this._bookCart);
        }

        public ActionResult AddToCart(int bookId, string returnUrl)
        {
            Book _book = _library._bookList.FirstOrDefault(b => b.ID == bookId);

            if (_book != null)
            {
                this._bookCart.AddBook(_book);
            }
            return RedirectToAction("Index", new { returnUrl });

        }

        public ActionResult cancelSession()
        {
            Session.Abandon();
            return RedirectToAction("Index","Home");
        }
    }    
}

SheridanLibrary/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SheridanLibrary.Domain.Entities;

namespace SheridanLibrary.Controllers
{
    public class HomeController : Controller
    {
        private Library _library;

        public HomeController()
        {
            _library = new Library();
        }
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult FilterProducts(string GenreFilter)
        {
            
            if (String.IsNullOrEmpty(GenreFilter))
            {
                return View("Library",_library._bookList);
            }
            else
            {
                BookGenre userSelect =(BookGenre) Enum.Parse(typeof(BookGenre),GenreFilter);
                
                return View("Library", _library.FilterBooks(b => b.Author == GenreFilter ));
            }
        }
        public ActionResult BookFilter(string title)
        {
            if (String.IsNullOrEmpty(title))
            {
                return View("Library",_library._bookList);
            }
            else
            {
                return View("Library", _library.FilterBooks(b => b.Name.IndexOf(title,StringComparison.OrdinalIgnoreCase)>=0));
            }
        }

        public ActionResult FilterRating(string rating)
        {
            decimal lowR = Decimal.Parse(rating);
            var rateList = from b in _library._bookList where b.Rating >= lowR select b;
            return View("Library", rateList);
        }
        public ActionResult Library()
        {
            return View("Library",_library._bookList);
        }
    }
}

SheridanLibrary/Views/Cart/Index.cshtml
@using SheridanLibrary.Domain.Entities
@model BookCart

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        <table border="1">
            <thead>
                <tr>
                    <td>Book Title</td>
                    <td>Author</td>
                    <td>Genre</td>
                    <td>Rating</td>
                </tr>
            </thead>
            <tbody>
                @foreach (Book book in Model._bookList)
                   {
                        <tr>
                            <td>@book.Name</td>
                            <td>@book.Author</td>
                            <td>@book.Genre</td>
                            <td>@book.Rating</td>
                        </tr>
                    }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3">Book Count:</td>
                    <td>@Model._bookList.Count()</td>
                </tr>
            </tfoot>
        </table>
        <div> <a href="@ViewBag.ReturnUrl">Continue to Library</a></div>
        <div>@Html.ActionLink("Cancel Order","cancelSession")</div>
    </div>
</body>
</html>

SheridanLibrary/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        <h1>Welcome to the Book Store</h1>
        @Html.ActionLink("Go to Library", "Library")
    </div>
</body>
</html>

SheridanLibrary/Views/Home/Library.cshtml
@using SheridanLibrary.Domain.Entities

@model IEnumerable<Book>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Library</title>
</head>
<body>
    <div>
        @using (Html.BeginForm("FilterProducts","Home"))
        {
            <p>Filter by Genre: </p>@Html.DropDownList("GenreFilter", new SelectList(Enum.GetNames(typeof(BookGenre))),"Show All")
            
            <input type="submit" value="Apply Filter" />
        }
        @using (Html.BeginForm("BookFilter", "Home"))
        {
            <p>Filter by Title: </p>@Html.TextBox("title")

            <input type="submit" value="Apply Filter" />
        }

       </div>
    <div>
        @using (Html.BeginForm("FilterRating","Home"))
        {
            <p>Filter by Rating:</p>@Html.TextBox("rating")
            <input type="submit" value="Apply Filter" />
        }
    </div>
    <div> <h1>Library</h1>

        @foreach (Book b in Model)
        {
            <p>Name: @b.Name.</p>
            <p>Author: @b.Author</p>
            <p>Genre: @b.Genre</p>
            <p>Rating: @b.Rating.ToString()</p>
            <p>
                @using (Html.BeginForm("AddToCart", "Cart"))
            {
                @Html.Hidden("bookId", b.ID)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                    <input type="submit" value="Add To Cart" />
                }
        </p>
        <br />
        } 
            

    </div>
</body>
</html>